/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Contatti from './Contatti';
import DatiAnagraficiCedentePrestatore from './DatiAnagraficiCedentePrestatore';
import IscrizioneREA from './IscrizioneREA';
import SedeCedentePrestatore from './SedeCedentePrestatore';
import StabileOrganizzazione from './StabileOrganizzazione';

/**
 * The CedentePrestatore model module.
 * @module model/CedentePrestatore
 * @version 1
 */
class CedentePrestatore {
    /**
     * Constructs a new <code>CedentePrestatore</code>.
     * @alias module:model/CedentePrestatore
     */
    constructor() { 
        
        CedentePrestatore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CedentePrestatore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CedentePrestatore} obj Optional instance to populate.
     * @return {module:model/CedentePrestatore} The populated <code>CedentePrestatore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CedentePrestatore();

            if (data.hasOwnProperty('dati_anagrafici')) {
                obj['dati_anagrafici'] = DatiAnagraficiCedentePrestatore.constructFromObject(data['dati_anagrafici']);
            }
            if (data.hasOwnProperty('sede')) {
                obj['sede'] = SedeCedentePrestatore.constructFromObject(data['sede']);
            }
            if (data.hasOwnProperty('stabile_organizzazione')) {
                obj['stabile_organizzazione'] = StabileOrganizzazione.constructFromObject(data['stabile_organizzazione']);
            }
            if (data.hasOwnProperty('iscrizione_rea')) {
                obj['iscrizione_rea'] = IscrizioneREA.constructFromObject(data['iscrizione_rea']);
            }
            if (data.hasOwnProperty('contatti')) {
                obj['contatti'] = Contatti.constructFromObject(data['contatti']);
            }
            if (data.hasOwnProperty('riferimento_amministrazione')) {
                obj['riferimento_amministrazione'] = ApiClient.convertToType(data['riferimento_amministrazione'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CedentePrestatore</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CedentePrestatore</code>.
     */
    static validateJSON(data) {
        // validate the optional field `dati_anagrafici`
        if (data['dati_anagrafici']) { // data not null
          DatiAnagraficiCedentePrestatore.validateJSON(data['dati_anagrafici']);
        }
        // validate the optional field `sede`
        if (data['sede']) { // data not null
          SedeCedentePrestatore.validateJSON(data['sede']);
        }
        // validate the optional field `stabile_organizzazione`
        if (data['stabile_organizzazione']) { // data not null
          StabileOrganizzazione.validateJSON(data['stabile_organizzazione']);
        }
        // validate the optional field `iscrizione_rea`
        if (data['iscrizione_rea']) { // data not null
          IscrizioneREA.validateJSON(data['iscrizione_rea']);
        }
        // validate the optional field `contatti`
        if (data['contatti']) { // data not null
          Contatti.validateJSON(data['contatti']);
        }
        // ensure the json data is a string
        if (data['riferimento_amministrazione'] && !(typeof data['riferimento_amministrazione'] === 'string' || data['riferimento_amministrazione'] instanceof String)) {
            throw new Error("Expected the field `riferimento_amministrazione` to be a primitive type in the JSON string but got " + data['riferimento_amministrazione']);
        }

        return true;
    }


}



/**
 * @member {module:model/DatiAnagraficiCedentePrestatore} dati_anagrafici
 */
CedentePrestatore.prototype['dati_anagrafici'] = undefined;

/**
 * @member {module:model/SedeCedentePrestatore} sede
 */
CedentePrestatore.prototype['sede'] = undefined;

/**
 * @member {module:model/StabileOrganizzazione} stabile_organizzazione
 */
CedentePrestatore.prototype['stabile_organizzazione'] = undefined;

/**
 * @member {module:model/IscrizioneREA} iscrizione_rea
 */
CedentePrestatore.prototype['iscrizione_rea'] = undefined;

/**
 * @member {module:model/Contatti} contatti
 */
CedentePrestatore.prototype['contatti'] = undefined;

/**
 * @member {String} riferimento_amministrazione
 */
CedentePrestatore.prototype['riferimento_amministrazione'] = undefined;






export default CedentePrestatore;

