/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DatiCassaPrevidenziale model module.
 * @module model/DatiCassaPrevidenziale
 * @version 1.1.3
 */
class DatiCassaPrevidenziale {
    /**
     * Constructs a new <code>DatiCassaPrevidenziale</code>.
     * @alias module:model/DatiCassaPrevidenziale
     */
    constructor() { 
        
        DatiCassaPrevidenziale.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DatiCassaPrevidenziale</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DatiCassaPrevidenziale} obj Optional instance to populate.
     * @return {module:model/DatiCassaPrevidenziale} The populated <code>DatiCassaPrevidenziale</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DatiCassaPrevidenziale();

            if (data.hasOwnProperty('tipo_cassa')) {
                obj['tipo_cassa'] = ApiClient.convertToType(data['tipo_cassa'], 'String');
            }
            if (data.hasOwnProperty('al_cassa')) {
                obj['al_cassa'] = ApiClient.convertToType(data['al_cassa'], 'Number');
            }
            if (data.hasOwnProperty('importo_contributo_cassa')) {
                obj['importo_contributo_cassa'] = ApiClient.convertToType(data['importo_contributo_cassa'], 'Number');
            }
            if (data.hasOwnProperty('imponibile_cassa')) {
                obj['imponibile_cassa'] = ApiClient.convertToType(data['imponibile_cassa'], 'Number');
            }
            if (data.hasOwnProperty('aliquota_iva')) {
                obj['aliquota_iva'] = ApiClient.convertToType(data['aliquota_iva'], 'Number');
            }
            if (data.hasOwnProperty('ritenuta')) {
                obj['ritenuta'] = ApiClient.convertToType(data['ritenuta'], 'String');
            }
            if (data.hasOwnProperty('natura')) {
                obj['natura'] = ApiClient.convertToType(data['natura'], 'String');
            }
            if (data.hasOwnProperty('riferimento_amministrazione')) {
                obj['riferimento_amministrazione'] = ApiClient.convertToType(data['riferimento_amministrazione'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DatiCassaPrevidenziale</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DatiCassaPrevidenziale</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tipo_cassa'] && !(typeof data['tipo_cassa'] === 'string' || data['tipo_cassa'] instanceof String)) {
            throw new Error("Expected the field `tipo_cassa` to be a primitive type in the JSON string but got " + data['tipo_cassa']);
        }
        // ensure the json data is a string
        if (data['ritenuta'] && !(typeof data['ritenuta'] === 'string' || data['ritenuta'] instanceof String)) {
            throw new Error("Expected the field `ritenuta` to be a primitive type in the JSON string but got " + data['ritenuta']);
        }
        // ensure the json data is a string
        if (data['natura'] && !(typeof data['natura'] === 'string' || data['natura'] instanceof String)) {
            throw new Error("Expected the field `natura` to be a primitive type in the JSON string but got " + data['natura']);
        }
        // ensure the json data is a string
        if (data['riferimento_amministrazione'] && !(typeof data['riferimento_amministrazione'] === 'string' || data['riferimento_amministrazione'] instanceof String)) {
            throw new Error("Expected the field `riferimento_amministrazione` to be a primitive type in the JSON string but got " + data['riferimento_amministrazione']);
        }

        return true;
    }


}



/**
 * @member {String} tipo_cassa
 */
DatiCassaPrevidenziale.prototype['tipo_cassa'] = undefined;

/**
 * @member {Number} al_cassa
 */
DatiCassaPrevidenziale.prototype['al_cassa'] = undefined;

/**
 * @member {Number} importo_contributo_cassa
 */
DatiCassaPrevidenziale.prototype['importo_contributo_cassa'] = undefined;

/**
 * @member {Number} imponibile_cassa
 */
DatiCassaPrevidenziale.prototype['imponibile_cassa'] = undefined;

/**
 * @member {Number} aliquota_iva
 */
DatiCassaPrevidenziale.prototype['aliquota_iva'] = undefined;

/**
 * @member {String} ritenuta
 */
DatiCassaPrevidenziale.prototype['ritenuta'] = undefined;

/**
 * @member {String} natura
 */
DatiCassaPrevidenziale.prototype['natura'] = undefined;

/**
 * @member {String} riferimento_amministrazione
 */
DatiCassaPrevidenziale.prototype['riferimento_amministrazione'] = undefined;






export default DatiCassaPrevidenziale;

