/**
 * Italian eInvoice API
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DatiRiepilogo from './DatiRiepilogo';
import DettaglioLinee from './DettaglioLinee';

/**
 * The DatiBeniServizi model module.
 * @module model/DatiBeniServizi
 * @version 1.0.0
 */
class DatiBeniServizi {
    /**
     * Constructs a new <code>DatiBeniServizi</code>.
     * @alias module:model/DatiBeniServizi
     */
    constructor() { 
        
        DatiBeniServizi.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DatiBeniServizi</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DatiBeniServizi} obj Optional instance to populate.
     * @return {module:model/DatiBeniServizi} The populated <code>DatiBeniServizi</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DatiBeniServizi();

            if (data.hasOwnProperty('dettaglio_linee')) {
                obj['dettaglio_linee'] = ApiClient.convertToType(data['dettaglio_linee'], [DettaglioLinee]);
            }
            if (data.hasOwnProperty('dati_riepilogo')) {
                obj['dati_riepilogo'] = ApiClient.convertToType(data['dati_riepilogo'], [DatiRiepilogo]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DatiBeniServizi</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DatiBeniServizi</code>.
     */
    static validateJSON(data) {
        if (data['dettaglio_linee']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['dettaglio_linee'])) {
                throw new Error("Expected the field `dettaglio_linee` to be an array in the JSON data but got " + data['dettaglio_linee']);
            }
            // validate the optional field `dettaglio_linee` (array)
            for (const item of data['dettaglio_linee']) {
                DettaglioLinee.validateJSON(item);
            };
        }
        if (data['dati_riepilogo']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['dati_riepilogo'])) {
                throw new Error("Expected the field `dati_riepilogo` to be an array in the JSON data but got " + data['dati_riepilogo']);
            }
            // validate the optional field `dati_riepilogo` (array)
            for (const item of data['dati_riepilogo']) {
                DatiRiepilogo.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/DettaglioLinee>} dettaglio_linee
 */
DatiBeniServizi.prototype['dettaglio_linee'] = undefined;

/**
 * @member {Array.<module:model/DatiRiepilogo>} dati_riepilogo
 */
DatiBeniServizi.prototype['dati_riepilogo'] = undefined;






export default DatiBeniServizi;

