/**
 * Italian eInvoice API v1
 * The [Italian eInvoice API][2] is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. The API also provides advanced features as encryption at rest, invoice validation, multiple upload formats, webhooks, event logging, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Anagrafica from './Anagrafica';
import IdFiscaleIVA from './IdFiscaleIVA';

/**
 * The DatiAnagraficiCedentePrestatore model module.
 * @module model/DatiAnagraficiCedentePrestatore
 * @version 1
 */
class DatiAnagraficiCedentePrestatore {
    /**
     * Constructs a new <code>DatiAnagraficiCedentePrestatore</code>.
     * @alias module:model/DatiAnagraficiCedentePrestatore
     */
    constructor() { 
        
        DatiAnagraficiCedentePrestatore.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DatiAnagraficiCedentePrestatore</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DatiAnagraficiCedentePrestatore} obj Optional instance to populate.
     * @return {module:model/DatiAnagraficiCedentePrestatore} The populated <code>DatiAnagraficiCedentePrestatore</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DatiAnagraficiCedentePrestatore();

            if (data.hasOwnProperty('id_fiscale_iva')) {
                obj['id_fiscale_iva'] = IdFiscaleIVA.constructFromObject(data['id_fiscale_iva']);
            }
            if (data.hasOwnProperty('codice_fiscale')) {
                obj['codice_fiscale'] = ApiClient.convertToType(data['codice_fiscale'], 'String');
            }
            if (data.hasOwnProperty('anagrafica')) {
                obj['anagrafica'] = Anagrafica.constructFromObject(data['anagrafica']);
            }
            if (data.hasOwnProperty('albo_professionale')) {
                obj['albo_professionale'] = ApiClient.convertToType(data['albo_professionale'], 'String');
            }
            if (data.hasOwnProperty('provincia_albo')) {
                obj['provincia_albo'] = ApiClient.convertToType(data['provincia_albo'], 'String');
            }
            if (data.hasOwnProperty('numero_iscrizione_albo')) {
                obj['numero_iscrizione_albo'] = ApiClient.convertToType(data['numero_iscrizione_albo'], 'String');
            }
            if (data.hasOwnProperty('data_iscrizione_albo')) {
                obj['data_iscrizione_albo'] = ApiClient.convertToType(data['data_iscrizione_albo'], 'Date');
            }
            if (data.hasOwnProperty('regime_fiscale')) {
                obj['regime_fiscale'] = ApiClient.convertToType(data['regime_fiscale'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DatiAnagraficiCedentePrestatore</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DatiAnagraficiCedentePrestatore</code>.
     */
    static validateJSON(data) {
        // validate the optional field `id_fiscale_iva`
        if (data['id_fiscale_iva']) { // data not null
          IdFiscaleIVA.validateJSON(data['id_fiscale_iva']);
        }
        // ensure the json data is a string
        if (data['codice_fiscale'] && !(typeof data['codice_fiscale'] === 'string' || data['codice_fiscale'] instanceof String)) {
            throw new Error("Expected the field `codice_fiscale` to be a primitive type in the JSON string but got " + data['codice_fiscale']);
        }
        // validate the optional field `anagrafica`
        if (data['anagrafica']) { // data not null
          Anagrafica.validateJSON(data['anagrafica']);
        }
        // ensure the json data is a string
        if (data['albo_professionale'] && !(typeof data['albo_professionale'] === 'string' || data['albo_professionale'] instanceof String)) {
            throw new Error("Expected the field `albo_professionale` to be a primitive type in the JSON string but got " + data['albo_professionale']);
        }
        // ensure the json data is a string
        if (data['provincia_albo'] && !(typeof data['provincia_albo'] === 'string' || data['provincia_albo'] instanceof String)) {
            throw new Error("Expected the field `provincia_albo` to be a primitive type in the JSON string but got " + data['provincia_albo']);
        }
        // ensure the json data is a string
        if (data['numero_iscrizione_albo'] && !(typeof data['numero_iscrizione_albo'] === 'string' || data['numero_iscrizione_albo'] instanceof String)) {
            throw new Error("Expected the field `numero_iscrizione_albo` to be a primitive type in the JSON string but got " + data['numero_iscrizione_albo']);
        }
        // ensure the json data is a string
        if (data['regime_fiscale'] && !(typeof data['regime_fiscale'] === 'string' || data['regime_fiscale'] instanceof String)) {
            throw new Error("Expected the field `regime_fiscale` to be a primitive type in the JSON string but got " + data['regime_fiscale']);
        }

        return true;
    }


}



/**
 * @member {module:model/IdFiscaleIVA} id_fiscale_iva
 */
DatiAnagraficiCedentePrestatore.prototype['id_fiscale_iva'] = undefined;

/**
 * @member {String} codice_fiscale
 */
DatiAnagraficiCedentePrestatore.prototype['codice_fiscale'] = undefined;

/**
 * @member {module:model/Anagrafica} anagrafica
 */
DatiAnagraficiCedentePrestatore.prototype['anagrafica'] = undefined;

/**
 * @member {String} albo_professionale
 */
DatiAnagraficiCedentePrestatore.prototype['albo_professionale'] = undefined;

/**
 * @member {String} provincia_albo
 */
DatiAnagraficiCedentePrestatore.prototype['provincia_albo'] = undefined;

/**
 * @member {String} numero_iscrizione_albo
 */
DatiAnagraficiCedentePrestatore.prototype['numero_iscrizione_albo'] = undefined;

/**
 * @member {Date} data_iscrizione_albo
 */
DatiAnagraficiCedentePrestatore.prototype['data_iscrizione_albo'] = undefined;

/**
 * @member {String} regime_fiscale
 */
DatiAnagraficiCedentePrestatore.prototype['regime_fiscale'] = undefined;






export default DatiAnagraficiCedentePrestatore;

