/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DatiRitenuta model module.
 * @module model/DatiRitenuta
 * @version 1.0.0
 */
class DatiRitenuta {
    /**
     * Constructs a new <code>DatiRitenuta</code>.
     * @alias module:model/DatiRitenuta
     */
    constructor() { 
        
        DatiRitenuta.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DatiRitenuta</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DatiRitenuta} obj Optional instance to populate.
     * @return {module:model/DatiRitenuta} The populated <code>DatiRitenuta</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DatiRitenuta();

            if (data.hasOwnProperty('tipo_ritenuta')) {
                obj['tipo_ritenuta'] = ApiClient.convertToType(data['tipo_ritenuta'], 'String');
            }
            if (data.hasOwnProperty('importo_ritenuta')) {
                obj['importo_ritenuta'] = ApiClient.convertToType(data['importo_ritenuta'], 'Number');
            }
            if (data.hasOwnProperty('aliquota_ritenuta')) {
                obj['aliquota_ritenuta'] = ApiClient.convertToType(data['aliquota_ritenuta'], 'Number');
            }
            if (data.hasOwnProperty('causale_pagamento')) {
                obj['causale_pagamento'] = ApiClient.convertToType(data['causale_pagamento'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DatiRitenuta</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DatiRitenuta</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['tipo_ritenuta'] && !(typeof data['tipo_ritenuta'] === 'string' || data['tipo_ritenuta'] instanceof String)) {
            throw new Error("Expected the field `tipo_ritenuta` to be a primitive type in the JSON string but got " + data['tipo_ritenuta']);
        }
        // ensure the json data is a string
        if (data['causale_pagamento'] && !(typeof data['causale_pagamento'] === 'string' || data['causale_pagamento'] instanceof String)) {
            throw new Error("Expected the field `causale_pagamento` to be a primitive type in the JSON string but got " + data['causale_pagamento']);
        }

        return true;
    }


}



/**
 * @member {String} tipo_ritenuta
 */
DatiRitenuta.prototype['tipo_ritenuta'] = undefined;

/**
 * @member {Number} importo_ritenuta
 */
DatiRitenuta.prototype['importo_ritenuta'] = undefined;

/**
 * @member {Number} aliquota_ritenuta
 */
DatiRitenuta.prototype['aliquota_ritenuta'] = undefined;

/**
 * @member {String} causale_pagamento
 */
DatiRitenuta.prototype['causale_pagamento'] = undefined;






export default DatiRitenuta;

