/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IscrizioneREA model module.
 * @module model/IscrizioneREA
 * @version 1.1.1
 */
class IscrizioneREA {
    /**
     * Constructs a new <code>IscrizioneREA</code>.
     * @alias module:model/IscrizioneREA
     */
    constructor() { 
        
        IscrizioneREA.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IscrizioneREA</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IscrizioneREA} obj Optional instance to populate.
     * @return {module:model/IscrizioneREA} The populated <code>IscrizioneREA</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IscrizioneREA();

            if (data.hasOwnProperty('ufficio')) {
                obj['ufficio'] = ApiClient.convertToType(data['ufficio'], 'String');
            }
            if (data.hasOwnProperty('numero_rea')) {
                obj['numero_rea'] = ApiClient.convertToType(data['numero_rea'], 'String');
            }
            if (data.hasOwnProperty('capitale_sociale')) {
                obj['capitale_sociale'] = ApiClient.convertToType(data['capitale_sociale'], 'Number');
            }
            if (data.hasOwnProperty('socio_unico')) {
                obj['socio_unico'] = ApiClient.convertToType(data['socio_unico'], 'String');
            }
            if (data.hasOwnProperty('stato_liquidazione')) {
                obj['stato_liquidazione'] = ApiClient.convertToType(data['stato_liquidazione'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IscrizioneREA</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IscrizioneREA</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['ufficio'] && !(typeof data['ufficio'] === 'string' || data['ufficio'] instanceof String)) {
            throw new Error("Expected the field `ufficio` to be a primitive type in the JSON string but got " + data['ufficio']);
        }
        // ensure the json data is a string
        if (data['numero_rea'] && !(typeof data['numero_rea'] === 'string' || data['numero_rea'] instanceof String)) {
            throw new Error("Expected the field `numero_rea` to be a primitive type in the JSON string but got " + data['numero_rea']);
        }
        // ensure the json data is a string
        if (data['socio_unico'] && !(typeof data['socio_unico'] === 'string' || data['socio_unico'] instanceof String)) {
            throw new Error("Expected the field `socio_unico` to be a primitive type in the JSON string but got " + data['socio_unico']);
        }
        // ensure the json data is a string
        if (data['stato_liquidazione'] && !(typeof data['stato_liquidazione'] === 'string' || data['stato_liquidazione'] instanceof String)) {
            throw new Error("Expected the field `stato_liquidazione` to be a primitive type in the JSON string but got " + data['stato_liquidazione']);
        }

        return true;
    }


}



/**
 * @member {String} ufficio
 */
IscrizioneREA.prototype['ufficio'] = undefined;

/**
 * @member {String} numero_rea
 */
IscrizioneREA.prototype['numero_rea'] = undefined;

/**
 * @member {Number} capitale_sociale
 */
IscrizioneREA.prototype['capitale_sociale'] = undefined;

/**
 * @member {String} socio_unico
 */
IscrizioneREA.prototype['socio_unico'] = undefined;

/**
 * @member {String} stato_liquidazione
 */
IscrizioneREA.prototype['stato_liquidazione'] = undefined;






export default IscrizioneREA;

