/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.invoicetronicSdk);
  }
}(this, function(expect, invoicetronicSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new invoicetronicSdk.DatiContratto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DatiContratto', function() {
    it('should create an instance of DatiContratto', function() {
      // uncomment below and update the code to test DatiContratto
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be.a(invoicetronicSdk.DatiContratto);
    });

    it('should have the property riferimentoNumeroLinea (base name: "riferimento_numero_linea")', function() {
      // uncomment below and update the code to test the property riferimentoNumeroLinea
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be();
    });

    it('should have the property idDocumento (base name: "id_documento")', function() {
      // uncomment below and update the code to test the property idDocumento
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be();
    });

    it('should have the property numItem (base name: "num_item")', function() {
      // uncomment below and update the code to test the property numItem
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be();
    });

    it('should have the property codiceCommessaConvenzione (base name: "codice_commessa_convenzione")', function() {
      // uncomment below and update the code to test the property codiceCommessaConvenzione
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be();
    });

    it('should have the property codiceCup (base name: "codice_cup")', function() {
      // uncomment below and update the code to test the property codiceCup
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be();
    });

    it('should have the property codiceCig (base name: "codice_cig")', function() {
      // uncomment below and update the code to test the property codiceCig
      //var instance = new invoicetronicSdk.DatiContratto();
      //expect(instance).to.be();
    });

  });

}));
